### ISSUE TITLE
fails to build with lmdbxx

### ISSUE THREAD

**Issue by maxice8** [Nheko-Reborn/nheko#555]
### Describe the bug

Failure to build with lmdbxx

```
src/../../src/Cache_p.h: In member function 'void Cache::saveStateEvent(lmdb::txn&, const lmdb::dbi&, const lmdb::dbi&, const string&, const T&)':
src/../../src/Cache_p.h:361:53: error: 'val' is not a member of 'lmdb'
  361 |                                               lmdb::val(e->state_key),
      |                                                     ^~~
src/../../src/Cache_p.h:362:53: error: 'val' is not a member of 'lmdb'
  362 |                                               lmdb::val(json(tmp).dump()));
      |                                                     ^~~
src/../../src/Cache_p.h:368:57: error: 'val' is not a member of 'lmdb'
  368 |                                   txn, membersdb, lmdb::val(e->state_key), lmdb::val(""));
      |                                                         ^~~
src/../../src/Cache_p.h:368:82: error: 'val' is not a member of 'lmdb'
  368 |                                   txn, membersdb, lmdb::val(e->state_key), lmdb::val(""));
      |                                                                                  ^~~
src/../../src/Cache_p.h: In lambda function:
src/../../src/Cache_p.h:386:50: error: 'val' is not a member of 'lmdb'
  386 |                             txn, statesdb, lmdb::val(to_string(e.type)), lmdb::val(json(e).dump()));
      |                                                  ^~~
src/../../src/Cache_p.h:386:80: error: 'val' is not a member of 'lmdb'
  386 |                             txn, statesdb, lmdb::val(to_string(e.type)), lmdb::val(json(e).dump()));
      |                                                                                ^~~
ninja: subcommand failed
```

### To Reproduce

Attempt to build with lmdbxx-1.0.0

**Comment by deepbluev7** [comment]
0.8.1 and lower only support lmdbxx < 1.0.0, if you want to use lmdbxx 1.0.0 or higher, use 0.8.2 or later :3

**Comment by deepbluev7** [comment]
Should happen in the next few days :3
